#!/bin/bash

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

if [ -d "venv" ]; then
    source venv/bin/activate
fi

export MOCK_HARDWARE="${MOCK_HARDWARE:-false}"
export RFID_MODE="${RFID_MODE:-hid}"
export RFID_HID_VENDOR_ID="${RFID_HID_VENDOR_ID:-0x1A86}"
export RFID_HID_PRODUCT_ID="${RFID_HID_PRODUCT_ID:-0xE010}"
export RFID_HID_OFFSET="${RFID_HID_OFFSET:-18}"
export RFID_HID_STRIP_HEX_DIGITS="${RFID_HID_STRIP_HEX_DIGITS:-6}"
export ULTRASONIC_ENABLED="${ULTRASONIC_ENABLED:-true}"
export ULTRASONIC_TRIG_PIN="${ULTRASONIC_TRIG_PIN:-23}"
export ULTRASONIC_ECHO_PIN="${ULTRASONIC_ECHO_PIN:-24}"
export ULTRASONIC_CLEAR_DISTANCE_CM="${ULTRASONIC_CLEAR_DISTANCE_CM:-40.0}"
export ULTRASONIC_MIN_VALID_DISTANCE_CM="${ULTRASONIC_MIN_VALID_DISTANCE_CM:-20.0}"
export ULTRASONIC_MAX_VALID_DISTANCE_CM="${ULTRASONIC_MAX_VALID_DISTANCE_CM:-450.0}"
export ULTRASONIC_RECHECK_INTERVAL="${ULTRASONIC_RECHECK_INTERVAL:-3.0}"
export ULTRASONIC_SAMPLE_INTERVAL="${ULTRASONIC_SAMPLE_INTERVAL:-0.06}"
export ULTRASONIC_SAFETY_TIMEOUT="${ULTRASONIC_SAFETY_TIMEOUT:-300}"
export ULTRASONIC_READ_TIMEOUT="${ULTRASONIC_READ_TIMEOUT:-0.5}"

if [ -z "$DISPLAY" ] && [ "$HEADLESS" != "true" ]; then
    echo "Nenhuma tela detectada (DISPLAY não configurado). O programa rodará em modo headless automaticamente."
fi
exec python3 main.py "$@"
